#!/bin/bash 

ampy --port /dev/serial/by-id/usb-Silicon_Labs_CP2102_USB_to_UART_Bridge_Controller_0001-if00-port0 put ./files/boot.py
#ampy --port /dev/ttyUSB0 put utils.py``
#ampy --port /dev/ttyUSB0 reset
