[package]
name = "pythonator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quote = "1.0.25"
syn = { version = "1.0.109", features = ["full","extra-traits","visit"] } 
