[build]
target = "avr-specs/avr-atmega328p.json"

[target.'cfg(target_arch = "avr")']
runner = "ravedude nano -cb 115200 -P /dev/serial/by-id/usb-FTDI_FT232R_USB_UART_A700eCzo-if00-port0"

[unstable]
build-std = ["core"]
build-std-features = ["compiler-builtins-mangled-names"]